### ISSUE TITLE
bug: return error on login action

### ISSUE THREAD

**Issue by 9ssi7** [BrianLeishman/go-imap#20]
We don't return login error anyway

<img width="725" alt="Screenshot 2024-07-30 at 18 28 54" src="https://github.com/user-attachments/assets/b7a5d874-94b6-4790-b2e0-6f32f7159322">

**Comment by BrianLeishman** [comment]
We are returning the err there, that's a [naked return](https://go.dev/tour/basics/7)

**Comment by 9ssi7** [comment]
When we look at it in more detail, we see that retry does not work properly because we do not return an error in retry. It keeps retrying forever.
<img width="428" alt="Screenshot 2024-07-30 at 18 49 58" src="https://github.com/user-attachments/assets/8e11f12a-5931-4c04-913b-48d05ee35c79">
<img width="1520" alt="Screenshot 2024-07-30 at 18 50 06" src="https://github.com/user-attachments/assets/f999bdee-9eb4-49dd-ac1e-d3f34b09769a">

**Comment by 9ssi7** [comment]
we must do this.

<img width="1234" alt="Screenshot 2024-07-30 at 18 51 58" src="https://github.com/user-attachments/assets/aed0c12e-e10d-4937-945c-efa3fbded824">

**Comment by BrianLeishman** [comment]
If the retry function wasn't receiving an error, then it wouldn't be retrying to log in. If `Login` was returning nil here like you say, then it wouldn't be retrying at all.

**Comment by 9ssi7** [comment]
So what could be the reason for it trying forever?

**Comment by BrianLeishman** [comment]
So this is because `RetryCount` global variable is set to 10. The login command itself [calls `Exec`](https://github.com/BrianLeishman/go-imap/blob/b77b778d8e9c2f80b11b3b82f5882951b6f9fe74/main.go#L397) with the global `RetryCount`, so this means that if login fails here it will try 10 times before it gives up. 

But then if we look at where the `New` function [calls `Login`](https://github.com/BrianLeishman/go-imap/blob/b77b778d8e9c2f80b11b3b82f5882951b6f9fe74/main.go#L200), this is also inside a retry loop that will retry with the same `RetryCount` variable. Since this is set to 10 in the code, by default it will run 10*10=100 times.

To change this you can update `imap.RetryCount` to something other than 10, but login will retry by `RetryCount` squared since that's how I wrote this forever ago.
